services:
  verdaccio:
    image: verdaccio/verdaccio:6.1.2
    container_name: "verdaccio"
    restart: unless-stopped
    environment:
      - VERDACCIO_PORT=5010
    ports:
      - "127.0.0.1:5010:5010/tcp"
    volumes:
      - "./conf/:/verdaccio/conf/"
